### ISSUE TITLE
`panic: op-batcher flag redefined: namespace-id`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/optimism#12]
When running on latest commit (c0bd1b58912d183d0d708d56bd3d5ca271cb132e) of celestia branch on this repo, I encounter this error:

```
op-batcher flag redefined: namespace-id
panic: op-batcher flag redefined: namespace-id

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0001aa300, {0x13077a0, 0xc000198db0}, {0xff7cd1, 0xc}, {0x100a033, 0x1c})
        /usr/local/go/src/flag/flag.go:980 +0x2f9
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:845
flag.(*FlagSet).String(0x10000005828b3?, {0xff7cd1, 0xc}, {0xc00003e1f8, 0x10}, {0x100a033, 0x1c})
        /usr/local/go/src/flag/flag.go:858 +0xac
github.com/urfave/cli.StringFlag.ApplyWithError.func1({0xff7cd1?, 0xc?})
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/flag_string.go:67 +0x94
github.com/urfave/cli.eachName({0xff7cd1?, 0x0?}, 0xc0000ad750)
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/flag.go:130 +0x93
github.com/urfave/cli.StringFlag.ApplyWithError({{0xff7cd1, 0xc}, {0x100a033, 0x1c}, {0xc000473050, 0x17}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/flag_string.go:62 +0xe9
github.com/urfave/cli.flagSet({0xff5a50, 0xa}, {0xc000232b00, 0x2d, 0x7efef5dd5c80?})
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/flag.go:115 +0x170
github.com/urfave/cli.(*App).newFlagSet(...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:185
github.com/urfave/cli.(*App).Run(0xc00054d340, {0xc0001981e0, 0x1, 0x1})
        /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:205 +0xea
main.main()
        /app/op-batcher/cmd/main.go:39 +0x334
```

**Comment by jcstein** [comment]
Resolved in https://github.com/celestiaorg/optimism/commit/34352c423a6c95b3e04115e91c5c690259283a73
