### ISSUE TITLE
cannot unmarshal dump

### ISSUE THREAD

**Issue by kw1knode** [celestiaorg/optimism#353]
go version go1.21.1 linux/amd64

v1.1.0-OP_v1.5.0-CN_v0.12.4

npm -v
10.1.0
node -v
v20.9.0
pnpm --version
8.15.1
Ubuntu 22.04.3 LTS

make devnet-up

```[INFO|02-09-2024 04:47:20] Devnet starting
[INFO|02-09-2024 04:47:20] Generating L1 genesis.
t=2024-02-09T04:47:23+0000 lvl=warn msg="L2OutputOracleStartingBlockNumber is 0, should only be 0 for fresh chains"
t=2024-02-09T04:47:23+0000 lvl=warn msg="L2OutputOracleStartingTimestamp is 0"
t=2024-02-09T04:47:23+0000 lvl=warn msg="RequiredProtocolVersion is empty"
t=2024-02-09T04:47:23+0000 lvl=warn msg="RecommendedProtocolVersion is empty"
t=2024-02-09T04:47:23+0000 lvl=crit msg="Application failed"                   message="cannot unmarshal dump: json: cannot unmarshal string into Go struct field DumpAccount.accounts.nonce of type uint64"
exit status 1
Traceback (most recent call last):
  File "/root/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/root/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/root/optimism/bedrock-devnet/devnet/__init__.py", line 120, in main
    devnet_deploy(paths)
  File "/root/optimism/bedrock-devnet/devnet/__init__.py", line 191, in devnet_deploy
    run_command([
  File "/root/optimism/bedrock-devnet/devnet/__init__.py", line 352, in run_command
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['go', 'run', 'cmd/main.go', 'genesis', 'l1', '--deploy-config', '/root/optimism/packages/contracts-bedrock/deploy-config/devnetL1.json', '--l1-allocs', '/root/optimism/.devnet/allocs-l1.json', '--l1-deployments', '/root/optimism/.devnet/addresses.json', '--outfile.l1', '/root/optimism/.devnet/genesis-l1.json']' returned non-zero exit status 1.
make: *** [Makefile:131: devnet-up] Error 1```

**Comment by kw1knode** [comment]
git checkout celestia-develop, built successfully

**Comment by tuxcanfly** [comment]
Will be fixed in rebase: https://github.com/ethereum-optimism/optimism/issues/9271
