### ISSUE TITLE
Panic runtime error on op-batcher

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/optimism#6]
On optimism branch of this repo, experiencing issues with Celestia Optimism rollup. Tutorial: https://docs.celestia.org/pr-preview/pr-490/

```
root@jcs-celopstia:~# lazydocker

+ docker logs --timestamps --follow --since=60m 4c84f6cd05f4fbf8449d985b0db106fb20688173d06ded3d85e6b4cdc32c5ce1

2023-03-23T15:35:48.975363594Z INFO [03-23|15:35:48.975] Initializing Batch Submitter
2023-03-23T15:35:49.016836567Z INFO [03-23|15:35:49.016] creating batch submitter                 submitter_addr=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC submitter_bal=904,625,697,166,532,776,746,648,320,380,374,280,103,671,755,200,316,906,558,262,375,061,821,325,312
2023-03-23T15:35:49.016863938Z INFO [03-23|15:35:49.016] Starting Batch Submitter
2023-03-23T15:35:49.016868438Z INFO [03-23|15:35:49.016] Batch Submitter started
2023-03-23T15:35:49.016871564Z INFO [03-23|15:35:49.016] starting pprof                           addr=0.0.0.0 port=6060
2023-03-23T15:35:49.016996540Z INFO [03-23|15:35:49.016] starting metrics server                  addr=0.0.0.0 port=7300
2023-03-23T15:35:50.020654745Z INFO [03-23|15:35:50.020] Starting batch-submitter work at safe-head safe=197ea3..4b588a:122
2023-03-23T15:35:51.021155594Z INFO [03-23|15:35:51.020] added L2 block to local state            block=fd4091..5a083b:123 tx_count=1 time=1,679,585,708
2023-03-23T15:35:51.021955250Z INFO [03-23|15:35:51.021] added L2 block to local state            block=44532c..1dadfc:124 tx_count=1 time=1,679,585,710
2023-03-23T15:35:51.022789200Z INFO [03-23|15:35:51.022] added L2 block to local state            block=d141ec..87158f:125 tx_count=1 time=1,679,585,712
2023-03-23T15:35:51.023594836Z INFO [03-23|15:35:51.023] added L2 block to local state            block=56bd52..6c1532:126 tx_count=1 time=1,679,585,714
2023-03-23T15:35:51.024373933Z INFO [03-23|15:35:51.024] added L2 block to local state            block=d7e95e..ca8218:127 tx_count=1 time=1,679,585,716
2023-03-23T15:35:51.025255865Z INFO [03-23|15:35:51.025] added L2 block to local state            block=a99986..2ef0b9:128 tx_count=1 time=1,679,585,718
2023-03-23T15:35:51.026285136Z INFO [03-23|15:35:51.025] added L2 block to local state            block=367b4a..f3ad44:129 tx_count=1 time=1,679,585,720
2023-03-23T15:35:51.027287816Z INFO [03-23|15:35:51.027] added L2 block to local state            block=300275..102885:130 tx_count=1 time=1,679,585,722
2023-03-23T15:35:51.028417858Z INFO [03-23|15:35:51.028] added L2 block to local state            block=a4464d..10a529:131 tx_count=1 time=1,679,585,724
2023-03-23T15:35:51.029196043Z INFO [03-23|15:35:51.029] added L2 block to local state            block=a7d4c5..9b686a:132 tx_count=1 time=1,679,585,726
2023-03-23T15:35:51.030076712Z INFO [03-23|15:35:51.029] added L2 block to local state            block=ae43ed..bb5e4e:133 tx_count=1 time=1,679,585,728
2023-03-23T15:35:51.030962280Z INFO [03-23|15:35:51.030] added L2 block to local state            block=a11d48..8cd550:134 tx_count=1 time=1,679,585,730
2023-03-23T15:35:51.031699637Z INFO [03-23|15:35:51.031] added L2 block to local state            block=c3bfba..46f299:135 tx_count=1 time=1,679,585,732
2023-03-23T15:35:51.033293699Z INFO [03-23|15:35:51.032] added L2 block to local state            block=1e7409..4a1298:136 tx_count=1 time=1,679,585,734
2023-03-23T15:35:51.033316452Z INFO [03-23|15:35:51.033] added L2 block to local state            block=df217a..b5464e:137 tx_count=1 time=1,679,585,736
2023-03-23T15:35:51.034300257Z INFO [03-23|15:35:51.034] added L2 block to local state            block=e1265e..fefcb6:138 tx_count=1 time=1,679,585,738
2023-03-23T15:35:51.035420780Z INFO [03-23|15:35:51.035] added L2 block to local state            block=2effa6..b932cf:139 tx_count=1 time=1,679,585,740
2023-03-23T15:35:51.036325855Z INFO [03-23|15:35:51.036] added L2 block to local state            block=44fed1..ed1bb6:140 tx_count=1 time=1,679,585,742
2023-03-23T15:35:51.037240369Z INFO [03-23|15:35:51.037] added L2 block to local state            block=e765c7..aec0a6:141 tx_count=1 time=1,679,585,744
2023-03-23T15:35:51.038226839Z INFO [03-23|15:35:51.037] added L2 block to local state            block=f25b07..685576:142 tx_count=1 time=1,679,585,746
2023-03-23T15:35:51.039215773Z INFO [03-23|15:35:51.039] added L2 block to local state            block=185f5a..041f24:143 tx_count=1 time=1,679,585,748
2023-03-23T15:35:51.040627178Z INFO [03-23|15:35:51.039] added L2 block to local state            block=0d741e..ad5641:144 tx_count=1 time=1,679,585,750
2023-03-23T15:35:51.041121535Z INFO [03-23|15:35:51.041] Created channel                          chID=fd04af..2a9b53 l1Head=53d9da..607607:95
2023-03-23T15:35:51.048652458Z panic: runtime error: index out of range [0] with length 0
2023-03-23T15:35:51.048700138Z
2023-03-23T15:35:51.048705298Z goroutine 28 [running]:
2023-03-23T15:35:51.048708514Z github.com/ethereum-optimism/optimism/op-batcher/batcher.(*TransactionManager).SendTransaction(0xc000328070, {0xfe6d58, 0xc00007ecc0}, {0xc0008b8240?, 0x21a, 0x3c96b6574faf04fd?})
2023-03-23T15:35:51.048713143Z 	/app/op-batcher/batcher/txmgr.go:69 +0x7e5
2023-03-23T15:35:51.048717230Z github.com/ethereum-optimism/optimism/op-batcher/batcher.(*BatchSubmitter).loop(0xc0002b4500)
2023-03-23T15:35:51.048720608Z 	/app/op-batcher/batcher/driver.go:278 +0x4ff
2023-03-23T15:35:51.048724034Z created by github.com/ethereum-optimism/optimism/op-batcher/batcher.(*BatchSubmitter).Start
2023-03-23T15:35:51.048727130Z 	/app/op-batcher/batcher/driver.go:152 +0x6c
```

<img width="1582" alt="Screenshot 2023-03-23 at 4 46 02 PM" src="https://user-images.githubusercontent.com/46639943/227260385-acd81125-9b20-4a8e-b37f-51e4664c527c.png">

**Comment by jcstein** [comment]
closed f15b8de13b4ad17a3957443c667fa7e1357da4fa
